### ISSUE TITLE
AirPods Pro always L: NA R: NA C: NA

### ISSUE THREAD

**Issue by denisoster** [slp/apodsmon#1]
Hi. I have AirPods Pro
I always get  only ` L: NA R: NA C: NA`
Tried running with superuser the result is the same.
bluez 5.55 installed.

OpenPods works on my phone

**Comment by slp** [comment]
It may be worth checking if the BT stack is seeing the packet from the AirPods. You can do that this way:

- Keep ```apodsmon``` running in a terminal.
- Open ```bluetoothctl``` in a different terminal.
- Open and close the AirPods case a couple times.

A message like this should appear in ```bluetoothctl```:
```
[CHG] Device XX:XX:XX:XX:XX:XX ManufacturerData Key: 0x004c
[CHG] Device XX:XX:XX:XX:XX:XX ManufacturerData Value:
  07 19 01 0f 20 55 66 b9 01 00 00 e3 c6 1e f5 b2  .... Uf.........
  d0 b0 3a 27 ce 3a 83 62 0a 15 e5                 ..:'.:.b...    
```

**Comment by denisoster** [comment]
bluetoothctl seeing AirPods

```
  07 19 01 0e 20 2b f9 8f 02 00 05 31 d7 d6 af 61  .... +.....1...a
  2a 20 39 cb 49 b1 9e 23 33 19 b6                 * 9.I..#3..
```

**Comment by slp** [comment]
That looks fine to me. It'd be hard to debug this from here, since I don't have the Airpods Pro. But, if you want to give it a try, I would start by playing around ```print_iter``` and ```print_fixed_iter``` to see if ```apodsmon``` sees the packet.

**Comment by BaruchWeka** [comment]
I have airpods pro and apodsmon works fine with them.

**Comment by slp** [comment]
@BaruchWeka Thanks for the confirmation. Closing this one for the time being.
